foodfiesta/cart/urls.py
from django.urls import path

from . import views

app_name = "cart"
urlpatterns = [
     path('demo/',views.demo.as_view(),name='demo'),
    path("cart/", views.cart.as_view(), name="cart"),
    path("addtocart", views.cart.as_view(), name="addtocart"),
    path("restaurant/", views.restaurant.as_view(), name="restaurant"),
    path("restaurant/<int:rest_id>", views.restaurant.as_view(),
         name="restaurant"),

    path("modify/quantity/", views.modify_quantity, name="quantity"),
    path("remove/item/<int:pk>/", views.CartItemDelete.as_view(),
         name="item-remove"),
    path("order/placed/", views.placeorder, name="placed-order"),
    path("myorder-list/", views.OrderList.as_view(), name="myorder-list"),
]

foodfiesta/foodfiesta/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('restaurant/',include('restaurantview.urls')),
    path('cart/',include('cart.urls')),
    path('adminview/',include('adminview.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foodfiesta/cart/models.py
from accounts.models import Address
from accounts.models import User
from django.db import models
from foodfiesta.constants import ORDER_STATUS, PENDING
from restaurantview.models import Restaurant, Delivery, Menu

from .managers import OrderManager, OrderitemManager


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    address = models.ForeignKey(Address, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    total_price = models.PositiveIntegerField(default=True)
    status = models.SmallIntegerField(choices=ORDER_STATUS, default=PENDING)
    delivery = models.ForeignKey(Delivery, on_delete=models.CASCADE, null=True,
                                 blank=True)

    objects = OrderManager()

    def __str__(self):
        return self.user.username + ' ' + str(self.restaurant)


class Orderitem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE, null=True,
                             blank=True)
    quantity = models.PositiveIntegerField()
    price = models.PositiveIntegerField()

    objects = OrderitemManager()

    def __str__(self):
        return str(self.order) + ' ' + str(self.menu)

foodfiesta/templates/backend/restaurantview/pages/product/addfooditem.html
{% extends 'backend/restaurantview/base.html' %}

{% load static %}
{% block main %}

<!-- Main Content -->
<main class="body-content">
  <!-- Navigation Bar -->
  {% include 'backend/restaurantview/navbar.html'%}

    <!-- Body Content Wrapper -->
    <div class="ms-content-wrapper">
      <div class="row">

        <div class="col-md-12">
          <!-- <div class="alert alert-success" role="alert">
            <strong>Well done!</strong> You successfully read this important alert message.
          </div> -->
        </div>



        <div class="col-xl-12 col-md-12">
          <div class="ms-panel ms-panel-fh">
            <div class="ms-panel-header">
              <h6>Add Food Form <a class="badge badge-secondary" href="#" style="float:right;">Add New Food Item</a></h6>
              
            </div>
            <div class="ms-panel-body">
              <!-- <form class="needs-validation clearfix" novalidate>
                <div class="form-row">
                  <div class="col-md-12 mb-3">
                    <label for="validationCustom18">Food Name</label>
                    <div class="input-group">
                      <input type="text" class="form-control" id="validationCustom18" placeholder="Food Name" value="Pizza" required>
                      <div class="valid-feedback">
                        Looks good!
                      </div>
                    </div>
                  </div>

                  <div class="col-md-12 mb-3">
                    <label for="validationCustom22">Select Catagory
                    </label>
                    <a href='#' style="float:right;"> Add New Category </a>
                    <div class="input-group">
                      <select class="form-control" id="validationCustom22" required>
                        <option value="">Catagory 1</option>
                        <option value="">Catagory 2</option>
                        <option value="">Catagory 3</option>
                        <option value="">Catagory 4</option>
                      </select>
                      <div class="invalid-feedback">
                        Please select a Catagory.
                      </div>
                    </div>
                  </div>
                  
                  <div class="col-md-6 mb-3">
                    <label for="validationCustom24">Quantity</label>
                    <div class="input-group">
                      <input type="text" class="form-control" id="validationCustom24" placeholder="01" required>
                      <div class="invalid-feedback">
                        Quantity
                      </div>
                    </div>
                  </div>
                  <div class="col-md-6 mb-3">
                    <label for="validationCustom25">Price</label>
                    <div class="input-group">
                      <input type="text" class="form-control" id="validationCustom25" placeholder="$10" required>
                      <div class="invalid-feedback">
                        Price
                      </div>
                    </div>
                  </div>
                  <div class="col-md-12 mb-3">
                    <label for="validationCustom12">Description</label>
                    <div class="input-group">
                      <textarea rows="5" id="validationCustom12" class="form-control" placeholder="Message" required></textarea>
                      <div class="invalid-feedback">
                        Please provide a Description.
                      </div>
                    </div>
                  </div>
                  <div class="col-md-12 mb-3">
                    <label for="validationCustom12">Product Image</label>
                    <div class="custom-file">
                      <input type="file" class="custom-file-input" id="validatedCustomFile">
                      <label class="custom-file-label" for="validatedCustomFile">Upload Images...</label>
                      <div class="invalid-feedback">Example invalid custom file feedback</div>
                    </div>
                  </div>
                </div>




              </form> -->
              <form method="POST" class='needs-validation clearfix' enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-secondary d-block add-food-item" type="submit">Add Food Item</button>
              </form>
            </div>
          </div>

        </div>


      </div>
    </div>


  </main>

{% endblock main %}


{% block psscript %}
  <script>
    'use strict';
      const openAlert = function(event){
        const resrult  = confirm(`Are you sure to Add Food Item, This item able to add another Resturant`)
        if(!result){ event.preventDefault()}
      } 

      const addFoodItemBtn   = document.getElementsByClassName('add-food-item'); 
      for(let i=0;i<addFoodItemBtn.length;i++){
        addFoodItemBtn[i].addEventListener('click',openAlert);
      }
  </script>
{% endblock psscript %}
  

foodfiesta/templates/backend/restaurantview/pages/product/customerlist.html
{% extends 'backend/restaurantview/base.html' %}

{% load static %}
{% block main %}

<!-- Main Content -->
<main class="body-content">

  <!-- Navigation Bar -->
  {% include 'backend/restaurantview/navbar.html' %}

  {% if object_list|length > 0 %}
  <div class="ms-content-wrapper">
    <div class="row">
      <div class="col-md-12">
        {% include 'backend/restaurantview/message.html'%}
        <div class="ms-panel">
          <div class="ms-panel-header">
            <h6>Customer Person</h6>
          </div>
          <div class="ms-panel-body">
            <div class="table-responsive">
              <div id="data-table-4_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
                <div class="row">
                  <div class="col-sm-12 table-responsive">
                    <table class="table table-hover thead-primary">
                      <thead>
                        <tr>
                          <th scope="col">No</th>
                          <th scope="col">Customer Name</th>
                          <th scope="col">Email</th>
                          <th scope="col">Orders</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for object in object_list %}
                        <tr>
                          <th scope="row">{{ forloop.counter }}</th>
                          <td>{{ object.username }}</td>
                          <td>{{ object.email }}</td>
                          <td>{{ object.order_set.count }}</td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                  {% include 'backend/restaurantview/pagination.html'%}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

    {% else %}
    <div class="ms-content-wrapper">
      <div class="row">

        <div class="col-md-12">
          <div class="alert alert-danger" role="alert">
              There is no <strong>Customer</strong> For Your Restaurant 
          </div>
        </div>
      </div>
    </div>
    {% endif %}
</main>
{% endblock main%}

foodfiesta/templates/backend/restaurantview/pages/product/deletefood.html
{% extends 'backend/restaurantview/base.html' %}

{% load static %}
{% block main %}

<!-- Main Content -->
<main class="body-content">
  <!-- Navigation Bar -->
  {% include 'backend/restaurantview/navbar.html'%}
  
    <!-- Body Content Wrapper -->
    <div class="ms-content-wrapper">
      <div class="row">
         <div class="col-md-12">
          <div class="ms-panel">
            <div class="ms-panel-header">
              <h6>Food Remove From Menu</h6>
            </div>
            <div class="ms-panel-body">    
                <form method="post">{% csrf_token %}
                    <p>Are you sure you want to delete "{{ object }}"?</p>
                    <button type="submit" class="btn btn-secondary">Confirm</button>
                </form>         
            </div>
          </div>
        </div>
      </div>
    </div>

  </main>
{% endblock main %}

foodfiesta/templates/backend/restaurantview/pages/product/deleterestaurant.html
{% extends 'backend/restaurantview/base.html' %}

{% load static %}
{% block main %}

<!-- Main Content -->
<main class="body-content">
  <!-- Navigation Bar -->
  {% include 'backend/restaurantview/navbar.html'%}
  
    <!-- Body Content Wrapper -->
    <div class="ms-content-wrapper">
      <div class="row">
         <div class="col-md-12">
          <div class="ms-panel">
            <div class="ms-panel-header">
              <h6>Restaurant Remove</h6>
            </div>
            <div class="ms-panel-body">    
                <form method="post">{% csrf_token %}
                  <p>Make sure to delete this "{{ object }}" Restaurant then it will also delete sub-brach and orders and delivery man?</p>
                  <p>Are you sure you want to delete "{{ object }}"?</p>
                  <p>Enter Reason Why you want close Restaurant</p>
                  {{ form.as_p }}
                    <button type="submit" class="btn btn-secondary confirm">Confirm</button>
                </form>         
            </div>
          </div>
        </div>
      </div>
    </div>

  </main>
{% endblock main %}

{% block psscript %}
  <script>
      'use strict';
      const confirmBtn   = document.getElementsByClassName('confirm')[0];
      const confirmAlert = function(event){
        const result  = confirm(`Are you sure to ${confirmBtn.innerHTML} The Resturant To Remove on this side`)
        if(!result){ event.preventDefault()}
      } 
      confirmBtn.addEventListener('click',confirmAlert);
  </script>
{% endblock psscript %}

foodfiesta/templates/backend/restaurantview/pages/product/editrestaurant.html
{% extends 'backend/restaurantview/base.html' %}

{% load static %}
{% block main %}

<!-- Main Content -->
<main class="body-content">
  <!-- Navigation Bar -->
  {% include 'backend/restaurantview/navbar.html'%}

    <!-- Body Content Wrapper -->
    <div class="ms-content-wrapper">
      <div class="row">

        <div class="col-md-12">
          <!-- <div class="alert alert-success" role="alert">
            <strong>Well done!</strong> You successfully read this important alert message.
          </div> -->
        </div>



        <div class="col-xl-12 col-md-12">
          <div class="ms-panel ms-panel-fh">
            <div class="ms-panel-header">
              <h6>Edit Branch Form</h6>
            </div>
            <div class="ms-panel-body">
              <form method="POST" class='needs-validation clearfix' enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-secondary d-block" type="submit">Update Branch</button>
              </form>
            </div>
          </div>

        </div>


      </div>
    </div>


  </main>

{% endblock main %}

foodfiesta/templates/backend/restaurantview/pages/product/fooddetail.html
{% extends 'backend/restaurantview/base.html' %}

{% load static %}
{% block main %}

<!-- Main Content -->
<main class="body-content">
    <!-- Navigation Bar -->
    {% include 'backend/restaurantview/navbar.html'%}

    <!-- Body Content Wrapper -->
    <div class="ms-content-wrapper">
        <div class="row">
            <div class="col-md-12">
                <div class="ms-panel">
                    <div class="ms-panel-header">
                        <h6>Food Details</h6>
                    </div>
                    <div class="ms-panel-body">

                        <div id="arrowSlider" class="ms-arrow-slider carousel slide" data-ride="carousel"
                             data-interval="false">
                            <div class="carousel-inner">
                                <div class="carousel-item active">
                                    <img class="d-block w-100"
                                         src="{% static 'backend/restaurantview/assets/img/costic/banner-1.jpg' %}"
                                         alt="First slide">
                                    <div class="carousel-caption d-none d-md-block">
                                        <h3 class="text-white">Pizaa img 1</h3>
                                    </div>
                                </div>
                                <div class="carousel-item">
                                    <img class="d-block w-100"
                                         src="{% static 'backend/restaurantview/assets/img/costic/banner-2.jpg' %}"
                                         alt="Second slide">
                                    <div class="carousel-caption d-none d-md-block">
                                        <h3 class="text-white">Pizaa img 2</h3>
                                    </div>
                                </div>
                                <div class="carousel-item">
                                    <img class="d-block w-100"
                                         src="{% static 'backend/restaurantview/assets/img/costic/banner-3.jpg' %}"
                                         alt="Third slide">
                                    <div class="carousel-caption d-none d-md-block">
                                        <h3 class="text-white">Pizaa img 3</h3>
                                    </div>
                                </div>
                            </div>
                            <a class="carousel-control-prev" href="#arrowSlider" role="button" data-slide="prev">
                                <span class="material-icons" aria-hidden="true">keyboard_arrow_left</span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="carousel-control-next" href="#arrowSlider" role="button" data-slide="next">
                                <span class="material-icons" aria-hidden="true">keyboard_arrow_right</span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>


            <div class=" col-md-6">
                <div class="ms-panel ms-panel-fh">
                    <div class="ms-panel-body">
                        <h4 class="section-title bold">Food Info</h4>
                        <table class="table ms-profile-information">
                            <tbody>

                            <tr>
                                <th scope="row">Price</th>
                                <td>$15</td>
                            </tr>
                            <tr>
                                <th scope="row">Food Category</th>
                                <td>Veg</td>
                            </tr>
                            <tr>
                                <th scope="row">Availiblity</th>
                                <td><span class="badge badge-pill badge-primary">In stock</span></td>
                            </tr>
                            <tr>
                                <th scope="row">Delivery Charges</th>
                                <td>Free</td>
                            </tr>


                            </tbody>
                        </table>
                        <div class="new">
                            <button type="button" class="btn btn-primary">Edit</button>
                            <button type="button" class="btn btn-secondary">Delete</button>
                        </div>

                    </div>
                </div>
            </div>

            <div class=" col-md-6">
                <div class="ms-panel ms-panel-fh">
                    <div class="ms-panel-body">

                        <h4 class="section-title bold">Food Details </h4>
                        <p class="description">Lorem Ipsum is simply dummy text of the printing and typesetting
                            industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when
                            an unknown printer took a galley of type and scrambled it to make a type specimen book type
                            and scrambled it to make a type specimen book.</p>


                    </div>
                    <div class="ms-quick-stats">
                        <div class="ms-stats-grid">
                            <i class="fa fa-bullhorn"></i>
                            <p class="ms-text-dark">1,033</p>
                            <span>Today Order</span>
                        </div>
                        <div class="ms-stats-grid">
                            <i class="fa fa-heart"></i>
                            <p class="ms-text-dark">3,039</p>
                            <span>Favourite</span>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </div>

</main>
{% endblock main %}



  

foodfiesta/templates/backend/restaurantview/pages/product/selectdashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Restaurant Dashboard</title>
    <!-- Iconic Fonts -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="{% static 'backend/restaurantview/assets/vendors/iconic-fonts/font-awesome/css/all.min.css' %}"
        rel="stylesheet">

    <link rel="stylesheet"
        href="{% static 'backend/restaurantview/assets/vendors/iconic-fonts/flat-icons/flaticon.css' %}">
    <link rel="stylesheet"
        href="{% static 'backend/restaurantview/assets/vendors/iconic-fonts/cryptocoins/cryptocoins.css' %}">
    <link rel="stylesheet"
        href="{% static 'backend/restaurantview/assets/vendors/iconic-fonts/cryptocoins/cryptocoins-colors.css' %}">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'backend/restaurantview/assets/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- jQuery UI -->
    <link href="{% static 'backend/restaurantview/assets/css/jquery-ui.min.css' %}" rel="stylesheet">
    <!-- Page Specific CSS (Slick Slider.css) -->


    {% block psstyle %}

    {% endblock psstyle %}


    <!-- Costic styles -->
    <link href="{% static 'backend/restaurantview/assets/css/style.css' %}" rel="stylesheet">
    <!-- Favicon -->
    <link rel="icon" type="image/png" sizes="32x32" href="{% static favicon.ico">

  <style>
    form input:focus,form select:focus,form textarea:focus{
      border:1px solid gainsboro;
      border-radius: 2px;
      padding: 4px;
    }
  </style>
</head>

<body class="ms-body ms-aside-left-open ms-primary-theme ">
  <!-- Preloader -->
  <div id="preloader-wrap">
    <div class="spinner spinner-8">
      <div class="ms-circle1 ms-child"></div>
      <div class="ms-circle2 ms-child"></div>
      <div class="ms-circle3 ms-child"></div>
      <div class="ms-circle4 ms-child"></div>
      <div class="ms-circle5 ms-child"></div>
      <div class="ms-circle6 ms-child"></div>
      <div class="ms-circle7 ms-child"></div>
      <div class="ms-circle8 ms-child"></div>
      <div class="ms-circle9 ms-child"></div>
      <div class="ms-circle10 ms-child"></div>
      <div class="ms-circle11 ms-child"></div>
      <div class="ms-circle12 ms-child"></div>
    </div>
  </div>
  <!-- Overlays -->
  <div class="ms-aside-overlay ms-overlay-left ms-toggler" data-target="#ms-side-nav" data-toggle="slideLeft"></div>
  <div class="ms-aside-overlay ms-overlay-right ms-toggler" data-target="#ms-recent-activity" data-toggle="slideRight">
  </div>
  <!-- Sidebar Navigation Left -->
  {% load static %}
<aside id="ms-side-nav" class="side-nav fixed ms-aside-scrollable ms-aside-left">

    <!-- Logo -->
    <div class="logo-sn ms-d-block-lg">
      <a class="pl-0 ml-0 text-center" href="{% url 'restaurantview:selectdashboard' %}"> <img src="{% static 'backend/restaurantview/assets/img/costic/Food_fiesta.png' %}" alt="logo"> </a>
    </div>

    <!-- Navigation -->
    <ul class="accordion ms-main-aside fs-14" id="side-nav-accordion">   
      <!-- Select Dashboard -->
      <li class="menu-item">
        <a href="{% url 'restaurantview:selectdashboard' %}">
          <span><i class="fas fa-hand-pointer"></i> Select DashBoard</span>
        </a>
      </li>
      <!-- Select Dahsboard -->
      <li class="menu-item">
        <a href="{% url 'restaurantview:addnewrestaurant' %}">
          <span><i class="fas fa-plus"></i>Add New Restaurant </span>
        </a>
      </li>
      <!-- Customers  end -->
    </ul>
  </aside>

  
  <main class="body-content">
    <!-- Navigation Bar -->
    <nav class="navbar ms-navbar">
    
        <div class="ms-aside-toggler ms-toggler pl-0" data-target="#ms-side-nav" data-toggle="slideLeft">
          <span class="ms-toggler-bar bg-primary"></span>
          <span class="ms-toggler-bar bg-primary"></span>
          <span class="ms-toggler-bar bg-primary"></span>
        </div>
    
        <div class="logo-sn logo-sm ms-d-block-sm">
          <a class="pl-0 ml-0 text-center navbar-brand mr-0"><img
              src="{% static 'backend/restaurantview/assets/img/costic/costic-logo-84x41.png' %}" alt="logo"> </a>
        </div>
    
        <ul class="ms-nav-list ms-inline mb-0" id="ms-nav-options">
          <li class="ms-nav-item ms-search-form pb-0 py-0">
            <form class="ms-form" method="post">
              <div class="ms-form-group my-0 mb-0 has-icon fs-14">
                {% csrf_token %}
                <input type="search" class="ms-form-input" name="search" placeholder="Search here..." value="">
                <i class="flaticon-search text-disabled"></i>
              </div>
            </form>
          </li>
          <li class="ms-nav-item ms-nav-user dropdown">
            <a href="#" id="userDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">   
              {% if user.profile %}
                <img class="ms-user-img ms-img-round float-right" src="{{ user.profile.url }}" alt="people">
              {% else %}
                <img class="ms-user-img ms-img-round float-right" src="{% static 'backend/restaurantview/assets/img/costic/customer-6.jpg' %}" alt="people">
              {% endif %} 
            </a>
          </li>
        </ul>
    
        <div class="ms-toggler ms-d-block-sm pr-0 ms-nav-toggler" data-toggle="slideDown" data-target="#ms-nav-options">
          <span class="ms-toggler-bar bg-primary"></span>
          <span class="ms-toggler-bar bg-primary"></span>
          <span class="ms-toggler-bar bg-primary"></span>
        </div>
    
      </nav>    
    {% if object_list|length > 0 %}
    <!-- Body Content Wrapper -->
    <div class=" ms-content-wrapper">

    <div class="row">
        <div class="col-md-12">
            <div class="row">
                {% include 'backend/restaurantview/message.html'%}
                {% for obj in object_list %}
                <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6">
                    <div class="ms-card">
                        <div class="ms-card-img">
                            <img src="{{ obj.pic.url }}" alt="card_img">
                        </div>
                        <div class="ms-card-body">

                            <div class="new">
                                <h6 class="mb-0"> {{ obj.name }}</a></h6>
                            </div>
                            <p> {{ obj.fooditem.description }}</p>
                            <div class="new mb-0">
                                <a href="{% url 'restaurantview:dashboard' obj.id %}"
                                    class="btn btn-primary btn-md btn-block">Manage</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

    </div>
    </div>

    </div>

    {% include 'backend/restaurantview/pagination.html'%}

    {% else %}
    <div class="ms-content-wrapper">
        <div class="row">

            <div class="col-md-12">
                <div class="alert alert-danger" role="alert">
                    In You <strong>Restaurant</strong> There is Not ant Menu Or Food
                </div>
            </div>
        </div>
    </div>
    {% endif %}
    </main>

    <!-- SCRIPTS -->
    <!-- Global Required Scripts Start -->
    <script src="{% static 'backend/restaurantview/assets/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'backend/restaurantview/assets/js/popper.min.js' %}"></script>
    <script src="{% static 'backend/restaurantview/assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'backend/restaurantview/assets/js/perfect-scrollbar.js' %}"></script>
    <script src="{% static 'backend/restaurantview/assets/js/jquery-ui.min.js' %}">
    </script>
    <!-- Global Required Scripts End -->

    {% block psscript %}

    {% endblock psscript %}

    <!-- Costic core JavaScript -->
    <script src="{% static 'backend/restaurantview/assets/js/framework.js' %}"></script>
    <!-- Settings -->
    <script src="{% static 'backend/restaurantview/assets/js/settings.js' %}"></script>
    </body>

</html>