foodfiesta/cart/urls.py
from django.urls import path

from . import views

app_name = "cart"
urlpatterns = [
     path('demo/',views.demo.as_view(),name='demo'),
    path("cart/", views.cart.as_view(), name="cart"),
    path("addtocart", views.cart.as_view(), name="addtocart"),
    path("restaurant/", views.restaurant.as_view(), name="restaurant"),
    path("restaurant/<int:rest_id>", views.restaurant.as_view(),
         name="restaurant"),

    path("modify/quantity/", views.modify_quantity, name="quantity"),
    path("remove/item/<int:pk>/", views.CartItemDelete.as_view(),
         name="item-remove"),
    path("order/placed/", views.placeorder, name="placed-order"),
    path("myorder-list/", views.OrderList.as_view(), name="myorder-list"),
]

foodfiesta/foodfiesta/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('restaurant/',include('restaurantview.urls')),
    path('cart/',include('cart.urls')),
    path('adminview/',include('adminview.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foodfiesta/restaurantview/urls.py
from django.urls import path
from restaurantview.views import Home, Profile, Menu, AddFood, FoodDetail, \
    Order, Invoice

app_name = 'restaurantview'
urlpatterns = [
    path('home', Home.as_view(), name='home'),
    path('profile', Profile.as_view(), name='profile'),

    # menu
    path('menu', Menu.as_view(), name='menu'),
    path('addfood', AddFood.as_view(), name='addfood'),
    path('fooddetail', FoodDetail.as_view(), name='fooddetail'),

    # order
    path('order', Order.as_view(), name='order'),

    # invoice
    path('invoice', Invoice.as_view(), name='invoice'),
]

foodfiesta/restaurantview/models.py
from django.db import models
from adminview.models import City,Fooditem
from accounts.models import User
from foodfiesta.constants import DELIVERY_STATUS,OPEN_STATUS,ACTIVE_STATUS
from restaurantview.managers import RestaurantManager

class Restaurant(models.Model):
    user        = models.ForeignKey(User,on_delete=models.CASCADE)
    parent      = models.ForeignKey('Restaurant',on_delete=models.CASCADE,blank=True,null=True)
    fooditem    = models.ManyToManyField(Fooditem,through='Menu')
    name        = models.CharField(max_length=75)
    address     = models.TextField(max_length=255)
    city        = models.ForeignKey(City,on_delete=models.CASCADE)
    contact     = models.CharField(max_length=13)
    open        = models.BooleanField(choices=OPEN_STATUS,default=False)
    active      = models.BooleanField(choices=ACTIVE_STATUS,default=False)
    pic         = models.ImageField(upload_to='restaurant/',blank=True,null=True)

    Restaurant = models.Manager()
    objects = RestaurantManager()

    class Meta:
        ordering = ['id']

    def __str__(self):
        return self.name

class Menu(models.Model):
    fooditem    = models.ForeignKey(Fooditem,on_delete=models.CASCADE)
    restaurant  = models.ForeignKey(Restaurant,on_delete=models.CASCADE)
    price       = models.PositiveIntegerField(default=0)
    available   = models.BooleanField(default=False)

    class Meta:
        ordering = ['id']
        
    def __str__(self):
        return self.fooditem.name    

class Delivery(models.Model):
    user       = models.OneToOneField(User,on_delete=models.CASCADE)
    restaurant = models.ForeignKey(Restaurant,on_delete=models.CASCADE)
    status     = models.BooleanField(choices=DELIVERY_STATUS,default=False)

    def __str__(self):
        return self.user.username

foodfiesta/restaurantview/forms.py
from django import forms
from .models import Restaurant,Delivery
from accounts.models import User
from django.contrib.auth.forms  import UserCreationForm

class ResturantRemoveForm(forms.Form):
    ''' Resturant Remove Request Form '''
    reason = forms.CharField(max_length=25,widget=forms.Textarea())
  

class DeliveryPersonForm(UserCreationForm):
    ''' Create user for delivery person by restaurant Request Form '''

    class Meta:
        model   = User
        fields  = ('first_name','last_name','username','email','password1','password2')

    def __init__(self, *args, **kwargs):
        super(DeliveryPersonForm, self).__init__(*args, **kwargs)

        for fieldname in self.fields:
            self.fields[fieldname].help_text = None 

foodfiesta/restaurantview/views.py
from django.shortcuts import render
from django.views import View


class Home(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'backend/restaurantview/index.html')


class Profile(View):
    def get(self, request, *args, **kwargs):
        return render(request,
                      'backend/restaurantview/pages/product/restaurant-profile.html')


class Menu(View):
    def get(self, request, *args, **kwargs):
        return render(request,
                      'backend/restaurantview/pages/product/foodgrid.html')


class AddFood(View):
    def get(self, request, *args, **kwargs):
        return render(request,
                      'backend/restaurantview/pages/product/addfood.html')


class FoodDetail(View):
    def get(self, request, *args, **kwargs):
        return render(request,
                      'backend/restaurantview/pages/product/fooddetail.html')


class Order(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'backend/restaurantview/pages/orders.html')


class Invoice(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'backend/restaurantview/pages/invoice.html')

foodfiesta/templates/backend/restaurantview/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Costic Dashboard</title>
    <!-- Iconic Fonts -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="{% static 'backend/restaurantview/assets/vendors/iconic-fonts/font-awesome/css/all.min.css' %}"
          rel="stylesheet">

    <link rel="stylesheet"
          href="{% static 'backend/restaurantview/assets/vendors/iconic-fonts/flat-icons/flaticon.css' %}">
    <link rel="stylesheet"
          href="{% static 'backend/restaurantview/assets/vendors/iconic-fonts/cryptocoins/cryptocoins.css' %}">
    <link rel="stylesheet"
          href="{% static 'backend/restaurantview/assets/vendors/iconic-fonts/cryptocoins/cryptocoins-colors.css' %}">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'backend/restaurantview/assets/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- jQuery UI -->
    <link href="{% static 'backend/restaurantview/assets/css/jquery-ui.min.css' %}" rel="stylesheet">
    <!-- Page Specific CSS (Slick Slider.css) -->
    <link href="{% static 'backend/restaurantview/assets/css/slick.css' %}" rel="stylesheet">
    <link href="{% static 'backend/restaurantview/assets/css/datatables.min.css' %}" rel="stylesheet">
    <!-- Costic styles -->
    <link href="{% static 'backend/restaurantview/assets/css/style.css' %}" rel="stylesheet">
    <!-- Favicon -->
    <link rel="icon" type="image/png" sizes="32x32" href="{% static favicon.ico">
</head>

<body class="ms-body ms-aside-left-open ms-primary-theme ">
<!-- Preloader -->
<div id="preloader-wrap">
    <div class="spinner spinner-8">
        <div class="ms-circle1 ms-child"></div>
        <div class="ms-circle2 ms-child"></div>
        <div class="ms-circle3 ms-child"></div>
        <div class="ms-circle4 ms-child"></div>
        <div class="ms-circle5 ms-child"></div>
        <div class="ms-circle6 ms-child"></div>
        <div class="ms-circle7 ms-child"></div>
        <div class="ms-circle8 ms-child"></div>
        <div class="ms-circle9 ms-child"></div>
        <div class="ms-circle10 ms-child"></div>
        <div class="ms-circle11 ms-child"></div>
        <div class="ms-circle12 ms-child"></div>
    </div>
</div>
<!-- Overlays -->
<div class="ms-aside-overlay ms-overlay-left ms-toggler" data-target="#ms-side-nav" data-toggle="slideLeft"></div>
<div class="ms-aside-overlay ms-overlay-right ms-toggler" data-target="#ms-recent-activity" data-toggle="slideRight">
</div>
<!-- Sidebar Navigation Left -->
{% include 'backend/restaurantview/sidebar.html' %}

{% block main %}

jpg' %}
{% endblock main %}

<!-- SCRIPTS -->
<!-- Global Required Scripts Start -->
<script src="{% static 'backend/restaurantview/assets/js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'backend/restaurantview/assets/js/popper.min.js' %}"></script>
<script src="{% static 'backend/restaurantview/assets/js/bootstrap.min.js' %}"></script>
<script src="{% static 'backend/restaurantview/assets/js/perfect-scrollbar.js' %}"></script>
<script src="{% static 'backend/restaurantview/assets/js/jquery-ui.min.js' %}">
</script>
<!-- Global Required Scripts End -->

{% block psscript %}

{% endblock psscript %}

<!-- Costic core JavaScript -->
<script src="{% static 'backend/restaurantview/assets/js/framework.js' %}"></script>
<!-- Settings -->
<script src="{% static 'backend/restaurantview/assets/js/settings.js' %}"></script>
</body>

</html>

foodfiesta/templates/backend/restaurantview/deliverydashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Restaurant Dashboard</title>
  <!-- Iconic Fonts -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="{% static 'backend/restaurantview/assets/vendors/iconic-fonts/font-awesome/css/all.min.css' %}" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'backend/restaurantview/assets/vendors/iconic-fonts/flat-icons/flaticon.css' %}">
  <link rel="stylesheet" href="{% static 'backend/restaurantview/assets/vendors/iconic-fonts/cryptocoins/cryptocoins.css' %}">
  <link rel="stylesheet" href="{% static 'backend/restaurantview/assets/vendors/iconic-fonts/cryptocoins/cryptocoins-colors.css' %}">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'backend/restaurantview/assets/css/bootstrap.min.css' %}" rel="stylesheet">
  
  <!-- jQuery UI -->
  <link href="{% static 'backend/restaurantview/assets/css/jquery-ui.min.css' %}" rel="stylesheet">
  <!-- Page Specific CSS (Slick Slider.css) -->

  <link href="{% static 'backend/restaurantview/assets/css/style.css' %}" rel="stylesheet">
  <!-- Favicon -->
  <link rel="icon" type="image/png" sizes="32x32" href="{% static favicon.ico">

  <style>
    form input:focus,form select:focus,form textarea:focus{
      border:1px solid gainsboro;
      border-radius: 2px;
      padding: 4px;
    }
  </style>
</head>

<!-- Main Content -->
<main class="body-content">
    <!-- Navigation Bar -->
    <nav class="navbar ms-navbar">

      <div class="ms-aside-toggler ms-toggler pl-0" data-target="#ms-side-nav" data-toggle="slideLeft">
        <span class="ms-toggler-bar bg-primary"></span>
        <span class="ms-toggler-bar bg-primary"></span>
        <span class="ms-toggler-bar bg-primary"></span>
      </div>
  
      <div class="logo-sn logo-sm ms-d-block-sm">
        <a class="pl-0 ml-0 text-center navbar-brand mr-0" href="index.html"><img
            src="{% static 'backend/restaurantview/assets/img/costic/costic-logo-84x41.png' %}" alt="logo"> </a>
      </div>
  
      <ul class="ms-nav-list ms-inline mb-0" id="ms-nav-options">
        <li class="ms-nav-item ms-search-form pb-0 py-0">
          <form class="ms-form" method="post">
            <div class="ms-form-group my-0 mb-0 has-icon fs-14">
              <input type="search" class="ms-form-input" name="search" placeholder="Search here..." value="">
              <i class="flaticon-search text-disabled"></i>
            </div>
          </form>
        </li>
        <li class="ms-nav-item ms-nav-user dropdown">
          <a href="#" id="userDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">   
            {% if user.profile %}
              <img class="ms-user-img ms-img-round float-right" src="{{ user.profile.url }}" alt="people">
            {% else %}
              <img class="ms-user-img ms-img-round float-right" src="{% static 'backend/restaurantview/assets/img/costic/customer-6.jpg' %}" alt="people">
            {% endif %} 
          </a>
          <ul class="dropdown-menu dropdown-menu-right user-dropdown" aria-labelledby="userDropdown">
            <li class="dropdown-menu-header">
              <h6 class="dropdown-header ms-inline m-0"><span class="text-disabled">Welcome, {{ user.first_name|title }} {{ user.last_name|title }}</span></h6>
            </li>
            <li class="dropdown-divider"></li>
            <li class="ms-dropdown-list">
              <a class="media fs-14 p-2" href="{% url 'restaurantview:profile' %}"> <span><i
                    class="flaticon-user mr-2"></i> Profile</span> </a>
              <a class="media fs-14 p-2" href="{% url 'restaurantview:profile' %}"> <span><i
                    class="flaticon-gear mr-2"></i> Account Settings</span> </a>
            </li>
            <li class="dropdown-divider"></li>
            <li class="dropdown-menu-footer">
              <a class="media fs-14 p-2" href="pages/prebuilt-pages/default-login.html"> <span><i
                    class="flaticon-shut-down mr-2"></i> Logout</span> </a>
            </li>
          </ul>
        </li>
      </ul>
  
      <div class="ms-toggler ms-d-block-sm pr-0 ms-nav-toggler" data-toggle="slideDown" data-target="#ms-nav-options">
          <span class="ms-toggler-bar bg-primary"></span>
        <span class="ms-toggler-bar bg-primary"></span>
        <span class="ms-toggler-bar bg-primary"></span>
      </div>
  
    </nav>    


    <aside id="ms-side-nav" class="side-nav fixed ms-aside-scrollable ms-aside-left">

      <!-- Logo -->
      <div class="logo-sn ms-d-block-lg">
        <a class="pl-0 ml-0 text-center" href="{% url 'restaurantview:home' %}"> <img src="{% static 'backend/restaurantview/assets/img/costic/Food_fiesta.png' %}" alt="logo"> </a>
      </div>
  
      <!-- Navigation -->
      <ul class="accordion ms-main-aside fs-14" id="side-nav-accordion">
      
        <li class="menu-item">
          <a href="#" class="active" data-toggle="collapse" data-target="#product" aria-expanded="false"
            aria-controls="product">
            <span><i class="fa fa-archive fs-16"></i>Delivery Dashboard</span>
          </a>
        </li>
        
      </ul>
  </aside>
  
    {% if order %}
      <!-- Body Content Wrapper -->
      <div class="ms-content-wrapper">
        <div class="row">
  
          <div class="col-md-12">
            <div class="col-12">
              {% include 'backend/restaurantview/message.html'%}
              
              <div class="ms-panel">
                <div class="ms-panel-header">
                  
                  {% if user %}
                  
                  {% for user in user %}
                  <h6 style="margin-left: 60%;">Your Name;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : &nbsp;&nbsp; {{ user.user.username }} </h6>
                  <h6 style="margin-left: 60%;">Your Tie-Up Restaurant : &nbsp;&nbsp;<span class="text-primary">{{ user.restaurant.name }}</span></h6>
                  <h6 style="margin-left: 60%;">Your Current Status &nbsp;&nbsp;&nbsp; : &nbsp;&nbsp;
                  {% if user.status == True %}
                  <span class="badge badge-success">Availabel</span>
                  {% else %}
                  <span class="badge badge-primary">Not Availabel</span>
                  {% endif %}
                </h6>
                  <h6 style="margin-left: 60%;">Change Status To &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; :{% if user.status == True %} 
                    &nbsp;&nbsp;
                    <a class="badge badge-primary" href="{% url 'restaurantview:changestatus' pk=user.id  %}">Not Availabel</a>
                    {% else %}
                    <a class="badge badge-success" href="{% url 'restaurantview:changestatus' pk=user.id  %}"">Availabel</a>
                    {% endif %}
                  </h6>
                  {% endfor %}
                  {% endif %}
                  <br><br>
                  <center><h6>Your Orders</h6></center>
                </div>
                <div class="ms-panel-body">
                  <div class="table-responsive">
                    <table class="table table-hover thead-primary">
                      <thead>
                        <tr>
                          <th scope="col">Order ID</th>
                          <th scope="col">Customer Name</th>
                          <th scope="col">Location</th>
                          <th scope="col">Contact</th>
                          <th scope="col">Order Status</th>
                          <th scope="col">Order Time</th>
                          <th scope="col">Price</th>
                          <th scope="col">Mark As Deliverd</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for object in order %}
                        <tr>
                          <th scope="row">{{ object.id }}</th>
                          <td>{{ object.user }}</td>
                          <td>{{ object.address.address|title }}</td>
                          <td>{{ object.address.contact }}</td>
                          <td>{% if object.status == 1 %}
                              <span class="badge badge-primary">Pending</span>
                              {% elif object.status == 3 %} 
                              <span class="badge badge-success">Delivered</span>
                              {% endif %}
                          </td>
                          <td>{{ object.date }}</td>
                          <td>{{ object.total_price }}</td>
                          <td>
                            
                            {% if object.status != 3 %}
                            <center><a title="Accept Order" href="{% url 'restaurantview:markasdelivered' pk=object.id  %}"><i style="font-size: 25px;" class="fa fa-check-circle ms-text-success"></i></a></center>    
                            {% endif %}
                          </td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
              {% include 'backend/restaurantview/pagination.html'%}
            </div>
          </div>
        </div>
      </div>
      {% else %}
      <div class="ms-content-wrapper">
        <div class="row">
  
          <div class="col-md-12">
            <div class="alert alert-danger" role="alert">
                Yet There is no <strong>Order</strong> For You..!
            </div>
          </div>
        </div>
      </div>
      {% endif %}
  
    </main>
    <script src="{% static 'backend/restaurantview/assets/js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'backend/restaurantview/assets/js/popper.min.js' %}"></script>
  <script src="{% static 'backend/restaurantview/assets/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'backend/restaurantview/assets/js/perfect-scrollbar.js' %}"></script>
  <script src="{% static 'backend/restaurantview/assets/js/jquery-ui.min.js' %}">
  </script>
     
  <!-- Costic core JavaScript -->
  <script src="{% static 'backend/restaurantview/assets/js/framework.js' %}"></script>
  <!-- Settings -->
  <script src="{% static 'backend/restaurantview/assets/js/settings.js' %}"></script>
  </body>

  </html>

foodfiesta/templates/backend/restaurantview/message.html
<div style="width: 80%;margin: 0 auto;">
  {% if messages %}
  {% for message in messages %}
      <li class="alert {{ message.tags }} text-center">{{ message }}</li>
    {% endfor %}
{% endif %}
</div>

foodfiesta/templates/backend/restaurantview/navbar.html
{% load static %}
<nav class="navbar ms-navbar">

    <div class="ms-aside-toggler ms-toggler pl-0" data-target="#ms-side-nav" data-toggle="slideLeft">
        <span class="ms-toggler-bar bg-primary"></span>
        <span class="ms-toggler-bar bg-primary"></span>
        <span class="ms-toggler-bar bg-primary"></span>
    </div>

    <div class="logo-sn logo-sm ms-d-block-sm">
        <a class="pl-0 ml-0 text-center navbar-brand mr-0" href="index.html"><img
                src="{% static 'backend/restaurantview/assets/img/costic/costic-logo-84x41.png' %}" alt="logo"> </a>
    </div>

    <ul class="ms-nav-list ms-inline mb-0" id="ms-nav-options">
        <li class="ms-nav-item ms-search-form pb-0 py-0">
            <form class="ms-form" method="post">
                <div class="ms-form-group my-0 mb-0 has-icon fs-14">
                    <input type="search" class="ms-form-input" name="search" placeholder="Search here..." value="">
                    <i class="flaticon-search text-disabled"></i>
                </div>
            </form>
        </li>

        <li class="ms-nav-item ms-nav-user dropdown">
            <a href="#" id="userDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <img
                    class="ms-user-img ms-img-round float-right"
                    src="{% static 'backend/restaurantview/assets/img/costic/customer-6.jpg' %}" alt="people"> </a>
            <ul class="dropdown-menu dropdown-menu-right user-dropdown" aria-labelledby="userDropdown">
                <li class="dropdown-menu-header">
                    <h6 class="dropdown-header ms-inline m-0"><span class="text-disabled">Welcome, Anny Farisha</span>
                    </h6>
                </li>
                <li class="dropdown-divider"></li>
                <li class="ms-dropdown-list">
                    <a class="media fs-14 p-2" href="{% url 'restaurantview:profile' %}"> <span><i
                            class="flaticon-user mr-2"></i> Profile</span> </a>
                    <a class="media fs-14 p-2" href="{% url 'restaurantview:profile' %}"> <span><i
                            class="flaticon-gear mr-2"></i> Account Settings</span> </a>
                </li>
                <li class="dropdown-divider"></li>
                <li class="dropdown-menu-footer">
                    <a class="media fs-14 p-2" href="pages/prebuilt-pages/default-login.html"> <span><i
                            class="flaticon-shut-down mr-2"></i> Logout</span> </a>
                </li>
            </ul>
        </li>
    </ul>

    <div class="ms-toggler ms-d-block-sm pr-0 ms-nav-toggler" data-toggle="slideDown" data-target="#ms-nav-options">
        <span class="ms-toggler-bar bg-primary"></span>
        <span class="ms-toggler-bar bg-primary"></span>
        <span class="ms-toggler-bar bg-primary"></span>
    </div>

</nav>

foodfiesta/templates/backend/restaurantview/pagination.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation conatiner">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item" ><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
        {% endif %}
        {% for i in page_obj.paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="page-item active"><a class="page-link"href="?page={{ i }}">{{ i }}</a></li>
            {% else %}
                <li class="page-item"><a class="page-link"href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>
        {% endif %}
    </ul>
</nav>    
{% endif %}

foodfiesta/templates/backend/restaurantview/sidebar.html
{% load static %}
<aside id="ms-side-nav" class="side-nav fixed ms-aside-scrollable ms-aside-left">

    <!-- Logo -->
    <div class="logo-sn ms-d-block-lg">
        <a class="pl-0 ml-0 text-center" href="index.html"> <img
                src="{% static 'backend/restaurantview/assets/img/costic/Food_fiesta.png' %}" alt="logo"> </a>
    </div>

    <!-- Navigation -->
    <ul class="accordion ms-main-aside fs-14" id="side-nav-accordion">

        <!-- foods -->
        <li class="menu-item">
            <a href="#" class="has-chevron" data-toggle="collapse" data-target="#product" aria-expanded="false"
               aria-controls="product">
                <span><i class="fa fa-archive fs-16"></i>Menus</span>
            </a>
            <ul id="product" class="collapse" aria-labelledby="product" data-parent="#side-nav-accordion">

                <li><a href="{% url 'restaurantview:menu' %}">Menus Grid</a></li>
                <li><a href="{% url 'restaurantview:addfood' %}">Add Food Item</a></li>
                <li><a href="{% url 'restaurantview:fooddetail' %}">Food Detail</a></li>
            </ul>
        </li>
        <!-- food end -->

        <!-- orders -->
        <li class="menu-item">
            <a href="{% url 'restaurantview:order' %}">
                <span><i class="fas fa-clipboard-list fs-16"></i>Orders</span>
            </a>
        </li>
        <!-- orders end -->

        <!-- restaurants -->
        <li class="menu-item">
            <a href="#" class="has-chevron" data-toggle="collapse" data-target="#restaurant" aria-expanded="false"
               aria-controls="product">
                <span><i class="fa fa-tasks fs-16"></i>Restaurants List</span>
            </a>
            <ul id="restaurant" class="collapse" aria-labelledby="product" data-parent="#side-nav-accordion">

                <li><a href="pages/product/restaurantlist.html">Restaurants List</a></li>
                <li><a href="pages/product/addrestaurant.html">Add Restaurant</a></li>
                <li><a href="pages/product/restaurantdetail.html">Restaurant Detail</a></li>
            </ul>
        </li>
        <!-- restaurants end -->

        <!-- customers-->

        <li class="menu-item">
            <a href="pages/customer/customerlist.html">
                <span><i class="fas fa-user-friends fs-16"></i>Customers </span>
            </a>
        </li>
        <!-- Customers  end -->


        <!-- delivery -->
        <li class="menu-item">
            <a href="pages/sales.html">
                <span><i class="fa fa-briefcase fs-16"></i>Delevery Persons</span>
            </a>
        </li>
        <!-- delivery-->


        <!-- delivery -->
        <li class="menu-item">
            <a href="#" class="has-chevron" data-toggle="collapse" data-target="#delivery" aria-expanded="false"
               aria-controls="product">
                <span><i class="fa fa-tasks fs-16"></i>Delivery Person</span>
            </a>
            <ul id="delivery" class="collapse" aria-labelledby="product" data-parent="#side-nav-accordion">

                <li><a href="pages/product/deliverylist.html">Delivery List</a></li>
                <li><a href="pages/product/adddelivery.html">Add Delivery Person</a></li>
                <li><a href="pages/product/deliverydetail.html">Person Detail</a></li>
            </ul>
        </li>
        <!-- delivery end -->


    </ul>


</aside>