foodfiesta/adminview/urls.py
from django.urls import path

from . import views

app_name = 'adminview'

urlpatterns = [
    path('index/', views.home, name='adminview_home'),
]

foodfiesta/cart/urls.py
from django.urls import path

from . import views

app_name = "cart"
urlpatterns = [
     path('demo/',views.demo.as_view(),name='demo'),
    path("cart/", views.cart.as_view(), name="cart"),
    path("addtocart", views.cart.as_view(), name="addtocart"),
    path("restaurant/", views.restaurant.as_view(), name="restaurant"),
    path("restaurant/<int:rest_id>", views.restaurant.as_view(),
         name="restaurant"),

    path("modify/quantity/", views.modify_quantity, name="quantity"),
    path("remove/item/<int:pk>/", views.CartItemDelete.as_view(),
         name="item-remove"),
    path("order/placed/", views.placeorder, name="placed-order"),
    path("myorder-list/", views.OrderList.as_view(), name="myorder-list"),
]

foodfiesta/foodfiesta/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('restaurant/',include('restaurantview.urls')),
    path('cart/',include('cart.urls')),
    path('adminview/',include('adminview.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foodfiesta/adminview/models.py
from django.db import models
from django.urls import reverse
from foodfiesta.constants import REQUEST_STATUS

class City(models.Model):
    name        = models.CharField(max_length=255)
    description = models.TextField(blank=True,null=True)

    def __str__(self):
        return self.name

class Category(models.Model):
    name        = models.CharField(max_length=75)
    description = models.TextField(blank=True,null=True)
    pic         = models.ImageField(upload_to='category/',blank=True,null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("adminview:category_detail", kwargs={"pk": self.pk})
    

class Fooditem(models.Model):
    category    = models.ForeignKey(Category,on_delete=models.CASCADE)
    name        = models.CharField(max_length=75)
    description = models.TextField(blank=True,null=True)
    pic         = models.ImageField(upload_to='fooditem/',blank=True,null=True)

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse("adminview:fooditem_detail", kwargs={"pk": self.pk})
    
class CancelRestaurantRequest(models.Model):
    restaurant = models.ForeignKey('restaurantview.Restaurant',on_delete=models.CASCADE)
    reason = models.TextField(blank=True,null=True)
    status = models.SmallIntegerField(choices=REQUEST_STATUS)

    def __str__(self):
        return str(self.restaurant.name) + " :- " + str(self.status)

foodfiesta/adminview/forms.py
from django import forms
from .models import *

class CategoryCreateForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Category Name'}),
            'description': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Category Description'}),
            'pic': forms.FileInput(attrs={'class': 'form-control', 'placeholder': 'Image'}),
        }

class FoodItemCreateForm(forms.ModelForm):
    class Meta:
        model = Fooditem
        fields = '__all__'
        widgets = {
            'category': forms.Select(attrs={'class': 'form-control', 'placeholder': 'FoodItem Name'}),
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'FoodItem name'}),
            'description': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'FoodItem Description'}),
            'pic' : forms.FileInput(attrs={'class': 'form-control', 'placeholder': 'Image Of Fooditem'}),
        }

class CityCreateForm(forms.ModelForm):
    class Meta:
        model = City
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'City name'}),
            'description': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'City Description'}),
        }

foodfiesta/adminview/views.py
from django.shortcuts import render


# Create your views here.
def home(request):
    return render(request, 'adminview/index.html')

foodfiesta/adminview/templates/adminview/fooditem/fooditem_confirm_delete.html
{% extends 'adminview/index.html' %}


{% block content %}
    
<form method="post">{% csrf_token %} 
    <h5>Are you sure you want to delete "<span class="text text-danger">{{ object }}</span>"?</h5> 
    <input class="btn btn-primary" type="submit" value="Confirm"> 
    <a class="btn btn-secondary" href="{% url 'adminview:allfooditem' %}">No,Cancel</a>
</form> 

{% endblock content %}
    

foodfiesta/adminview/templates/adminview/fooditem/fooditem_detail.html
{% extends 'adminview/index.html' %}

{% block content %}
    


<div class="ms-content-wrapper">
    <div class="row">

      <div class="col-md-12">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb pl-0">
            <li class="breadcrumb-item"><a href="{% url 'adminview:adminview_home' %}"><i class="material-icons">home</i> Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'adminview:allcategory' %}">Category List</a></li>
            <li class="breadcrumb-item active" aria-current="page">FoodItem Detail</li>
          </ol>
        </nav>
      </div>
       <div class="col-md-6">
        <div class="ms-panel">
          <div class="ms-panel-header">
            <h6>FoodItem Image</h6>
          </div>
          <div class="ms-panel-body">

            <div id="arrowSlider" class="ms-arrow-slider carousel slide" data-ride="carousel" data-interval="false">
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <img style="height: 300px;width: 100%;" class="d-block " src="{{ fooditem.pic.url }}" alt="First slide">
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>


<div class=" col-md-6">
        <div class="ms-panel ms-panel-fh">
          <div class="ms-panel-body">
            <center><h4 class="section-title bold">Category Info</h4></center>
            <table class="table ms-profile-information">
              <tbody>

                <tr>
                  <th scope="row">FoodItem</th>
                  <td>{{ fooditem.name }}</td>
                </tr>
                <tr>
                    <th scope="row">Category</th>
                    <td>{{ fooditem.category.name }}</td>
                  </tr>
                <tr>
                  <th scope="row">Description</th>
                  <td>{{ fooditem.description }}</td>
                </tr>
              </tbody>
            </table>
            <div class="new">
              <a class="btn btn-primary mt-4 d-block w-50" href="{% url 'adminview:fooditem_update' pk=fooditem.pk %}">Update</a>  
              <a class="btn btn-secondary mt-4 d-block w-50" href="{% url 'adminview:fooditem_delete' pk=fooditem.pk %}">Delete</a>  
              
            </div>

          </div>
        </div>
      </div>
</div>
</div>

{% endblock content %}
    

foodfiesta/adminview/templates/adminview/fooditem/fooditem_form.html
{% extends 'adminview/index.html' %}

{% block content %}
    
<div class="ms-content-wrapper">
    <div class="row">

      <div class="col-md-12">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb breadcrumb-arrow has-gap has-bg">
            <li class="breadcrumb-item"><a href="{% url 'adminview:adminview_home' %}"><i class="material-icons">home</i> Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'adminview:allfooditem' %}">FoodItem Grid</a></li>
            <li class="breadcrumb-item active" aria-current="page">Add FoodItem</li>
          </ol>
        </nav>

        {% if messages %}
                            <ul class="messages">
                                {% for message in messages %}
                                <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                                    {{ message }}
                                </li>
                                {% endfor %}
                            </ul>
                            {% endif %}


      </div>
      
      <div class="col-xl-12 col-md-12">
        <div class="ms-panel">
          <div class="ms-panel-header">
            <center>
            <h6>Add Fooditem</h6>
        </center>
          </div>
          <div class="ms-panel-body">
            <form method="POST">
              <div class="form-row">
                <div class="col-md-12 mb-3">
          {% csrf_token %}

            {% for field in form %}


            <div class="form-group">
                <label>{{ field.label}}</label>
                {{ field }}

            </div>
            {% endfor %}

            <button class="btn btn-primary mt-4 d-block w-100" type="submit">Create FoodItem</button>
        </div>
        </form>
        </div>
        </div>
      </div>
      </div>
</div>



          
{% endblock content %}
    

foodfiesta/adminview/templates/adminview/fooditem/fooditem_update.html
{% extends 'adminview/index.html' %}

{% block content %}
    
<div class="ms-content-wrapper">
    <div class="row">

      <div class="col-md-12">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb breadcrumb-arrow has-gap has-bg">
            <li class="breadcrumb-item"><a href="#"><i class="material-icons">home</i> Home</a></li>
            <li class="breadcrumb-item"><a href="#">Menu</a></li>
            <li class="breadcrumb-item active" aria-current="page">Update FoodItem</li>
          </ol>
        </nav>

        {% if messages %}
                            <ul class="messages">
                                {% for message in messages %}
                                <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                                    {{ message }}
                                </li>
                                {% endfor %}
                            </ul>
                            {% endif %}


      </div>
      
      <div class="col-xl-12 col-md-12">
        <div class="ms-panel">
          <div class="ms-panel-header">
            <center>
            <h6>Update FoodItem</h6>
        </center>
          </div>
          <div class="ms-panel-body">
            <form method="POST">
              <div class="form-row">
                <div class="col-md-12 mb-3">
          {% csrf_token %}

            {% for field in form %}


            <div class="form-group">
                <label>{{ field.label}}</label>
                {{ field }}

            </div>
            {% endfor %}

            <button class="btn btn-primary mt-4 d-block w-100" type="submit">Update</button>
        </div>
        </form>
        </div>
        </div>
      </div>
      </div>
</div>



          
{% endblock content %}
    

foodfiesta/adminview/templates/adminview/fooditem/fooditemgird.html
{% extends 'adminview/index.html' %}

{% block content %}

<div class="ms-content-wrapper">

    <div class="row">
      <div class="col-md-12">
        <nav aria-label="breadcrumb" class="new">
          <ol class="breadcrumb breadcrumb-arrow has-gap has-bg">
            <li class="breadcrumb-item"><a href="{% url 'adminview:adminview_home' %}"><i class="material-icons">home</i> Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">FoodItem Grid</li>
          </ol>
        </nav>
        
        
            
        {% if object_list %}
          <div class="row">
            {% for food in object_list  %}
            <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6">
                <div class="ms-card">
                  <div class="ms-card-img">
                    <img src="{{ food.pic.url }}" alt="card_img">
                  </div>
                  <div class="ms-card-body">

                    <div class="new">
                      <h6 class="mb-0">{{ food.name }} </h6>
                    </div>
                    <div class="new">
                        <h6 class="mb-0">{{ food.category.name }} </h6>
                      </div>
                    <p style="width: 200px; height: 170px;">{{ food.description }}</p>
                    <div class="new mb-0">
                      <a class="btn grid-btn mt-0 btn-sm btn-success" href="{{ food.get_absolute_url }}">View</a>
                      <a class="btn grid-btn mt-0 btn-sm btn-secondary" href="{% url 'adminview:fooditem_update' pk=food.pk %}">Edit</a>
                      <a class="btn grid-btn mt-0 btn-sm btn-primary" href="{% url 'adminview:fooditem_delete' pk=food.pk %}">Delete</a>
                      
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
              </div>
              {% endif %}
              </div>
              
              
            </div>
    </div>
        

{% endblock content %}
    